Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"

  # Production VM
  config.vm.define "petclinic-prod" do |prod|
    prod.vm.hostname = "petclinic-prod"
    prod.vm.network "private_network", ip: "192.168.56.200"

    prod.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    config.vm.provision "shell", path: "prod_vm_provision.sh"
    config.ssh.insert_key = true
  end

  # Staging VM
  config.vm.define "petclinic-stage" do |stage|
    stage.vm.hostname = "petclinic-stage"
    stage.vm.network "private_network", ip: "192.168.56.201"

    stage.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    config.vm.provision "shell", path: "prod_vm_provision.sh"
    config.ssh.insert_key = true
  end
end

